config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: %i[ new create ]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "home#index"

  constraints Clearance::Constraints::SignedIn.new do
    root to: "products#index", as: :signed_in_root
  end

  get 'about' => 'home#about', as: 'about'
  get 'contact' => 'home#contact', as: 'contact'
  resources :products, only: :show
  resources :sessions
  resources :orders, only: %i[ create update show ]
  resources :users, only: %i[ show ]
  get 'cart' => 'orders#cart', as: 'cart'
  post 'add-to-cart' => 'orders#add_to_cart', as: 'add_to_cart'
  post 'remove-from-cart' => 'orders#remove_from_cart', as: 'remove_from_cart'
  get 'shipping' => 'orders#shipping', as: 'shipping'
  get 'checkout' => 'orders#shipping', as: 'checkout'
  get 'review' => 'orders#review', as: 'review'

  resources :charges, only: %i[ create ]
  post 'stripe-webhook' => "charges#stripe_webhook"
  get 'charges/success' => 'charges#success', as: 'success'
  get 'charges/cancel' => 'charges#cancel', as: 'cancel'

  namespace 'admin' do
    resources :products, except: :show
    resources :settings, :users, :promotions
    resources :messages, only: %i[ index show destroy ]
    resources :orders, only: %i[ index update show destroy ]
  end
end

app/models/admin/promotion.rb
class Admin::Promotion < ApplicationRecord
  validates :code, format: { with: /\A[a-zA-Z0-9]+\z/,
    message: "only allows letters and numbers" }
  validates :name, length: { maximum: 20 }
  validates :starts_at, presence: true
  validate :check_only_percentage_or_dollar

    scope :active, -> { where("admin_promotions.starts_at < ? AND admin_promotions.ends_at > ?", Time.now, Time.now) }

  def active?
    self.starts_at < Time.now && !expired?
  end

  def expired?
    self.ends_at.present? && self.ends_at < Time.now
  end

  private

  def check_only_percentage_or_dollar
    errors.add(:base, 'only 1 of percentage or a dollar discount is allowed') if discount_percentage.present? && discount_dollars.present?
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::AdminController
  before_action :set_admin_promotion, only: %i[ show edit update destroy ]

  def index
    @admin_promotions = Admin::Promotion.all
  end

  def show
  end

  def new
    @admin_promotion = Admin::Promotion.new
  end

  def edit
  end

  def create
    @admin_promotion = Admin::Promotion.new(admin_promotion_params)

    respond_to do |format|
      if @admin_promotion.save
        format.html { redirect_to @admin_promotion, notice: "Promotion was successfully created." }
        format.json { render :show, status: :created, location: @admin_promotion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_promotion.update(admin_promotion_params)
        format.html { redirect_to @admin_promotion, notice: "Promotion was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_promotion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_promotion.destroy
    respond_to do |format|
      format.html { redirect_to admin_promotions_url, notice: "Promotion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_promotion
      @admin_promotion = Admin::Promotion.find(params[:id])
    end

    def admin_promotion_params
      params.require(:admin_promotion).permit(:code, :name, :has_free_shipping, :discount_percentage, :discount_dollars, :starts_at, :ends_at)
    end
end

app/helpers/admin/promotions_helper.rb
module Admin::PromotionsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/admin/promotions/_form.html.haml
= form_for @admin_promotion do |f|
  .row
    .col-md-5
      - if @admin_promotion.errors.any?
        #error_explanation
          %h2= "#{pluralize(@admin_promotion.errors.count, "error")} prohibited this promotion from being saved:"
          %ul
            - @admin_promotion.errors.full_messages.each do |message|
              %li= message

      .form-group
        = f.label :code
        = f.text_field :code, class: 'form-control', placeholder: 'SomeCode'
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :discount_percentage
        %small.text-muted (1-100)
        = f.number_field :discount_percentage, class: 'form-control'

      .form-group
        = f.label :discount_dollars
        %small.text-muted (any dollar amount)
        = f.number_field :discount_dollars, class: 'form-control'

      .form-group
        = f.label :has_free_shipping
        = f.check_box :has_free_shipping, class: 'form-control'
  .row
    .col-md-3
      .form-group
        = f.label :starts_at
        = f.datetime_select :starts_at, {}, class: 'form-control'
    .col-md-3
      .form-group
        = f.label :ends_at
        = f.datetime_select :ends_at, {}, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-base'

app/views/admin/promotions/edit.html.haml
%h1 Editing admin_promotion

= render 'form'

= link_to 'Show', @admin_promotion
\|
= link_to 'Back', admin_promotions_path

app/views/admin/promotions/index.html.haml
%h1 Promotions

%table.table
  %thead
    %tr
      %th
      %th Code
      %th Name
      %th Discount %
      %th Discount $
      %th Free shipping
      %th Start
      %th End
      %th
      %th
      %th

  %tbody
    - @admin_promotions.each do |admin_promotion|
      %tr
        %td
          - if admin_promotion.active?
            .badge.badge-success Active
          - elsif admin_promotion.expired?
            .badge.badge-danger Expired
        %td= admin_promotion.code
        %td= admin_promotion.name
        %td= number_to_percentage(admin_promotion.discount_percentage, precision: 2)
        %td= number_to_currency(admin_promotion.discount_dollars) if admin_promotion.discount_dollars
        %td
          - unless admin_promotion.has_free_shipping?
            = fa_icon 'check'
        %td= nice_datetime_concise(local_time(admin_promotion.starts_at)) if admin_promotion.starts_at
        %td= nice_datetime_concise(local_time(admin_promotion.ends_at)) if admin_promotion.ends_at
        %td= link_to 'Show', admin_promotion
        %td= link_to 'Edit', edit_admin_promotion_path(admin_promotion)
        %td= link_to 'Destroy', admin_promotion, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Promotion', new_admin_promotion_path

app/views/admin/promotions/new.html.haml
%h1 New Promotion

%p Only (1) discount percentage or dollar amount can be applied. Free shipping can be chosen separately.

= render 'form'

= link_to 'Back', admin_promotions_path

app/views/admin/promotions/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @admin_promotion.code
%p
  %b Name:
  = @admin_promotion.name
%p
  %b Discount percentage:
  = @admin_promotion.discount_percentage
%p
  %b Start:
  = @admin_promotion.starts_at
%p
  %b End:
  = @admin_promotion.ends_at

= link_to 'Edit', edit_admin_promotion_path(@admin_promotion)
\|
= link_to 'Back', admin_promotions_path
\|
= link_to 'All', admin_promotions_path