config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: %i[ new create ]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "home#index"

  constraints Clearance::Constraints::SignedIn.new do
    root to: "products#index", as: :signed_in_root
  end

  get 'about' => 'home#about', as: 'about'
  get 'contact' => 'home#contact', as: 'contact'
  resources :products, only: :show
  resources :sessions
  resources :orders, only: %i[ create update show ]
  resources :users, only: %i[ show ]
  get 'cart' => 'orders#cart', as: 'cart'
  post 'add-to-cart' => 'orders#add_to_cart', as: 'add_to_cart'
  post 'remove-from-cart' => 'orders#remove_from_cart', as: 'remove_from_cart'
  get 'shipping' => 'orders#shipping', as: 'shipping'
  get 'checkout' => 'orders#shipping', as: 'checkout'
  get 'review' => 'orders#review', as: 'review'

  resources :charges, only: %i[ create ]
  post 'stripe-webhook' => "charges#stripe_webhook"
  get 'charges/success' => 'charges#success', as: 'success'
  get 'charges/cancel' => 'charges#cancel', as: 'cancel'

  namespace 'admin' do
    resources :products, except: :show
    resources :settings, :users, :promotions
    resources :messages, only: %i[ index show destroy ]
    resources :orders, only: %i[ index update show destroy ]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_rich_text :description
  has_many :order_items
  validates :name, presence: true
  validates :price, numericality: {  greater_than_or_equal_to: 0, allow_nil: true }

  before_destroy :check_if_in_any_orders

  scope :master, -> { where(master_product_id: nil) }
  scope :active, -> { where(is_active: true)}

  has_many_attached :images
  belongs_to :master_product, class_name: 'User', foreign_key: 'master_product_id', optional: true

  def check_if_in_any_orders
    if order_items.any?
      errors.add(:base, 'can not be destroyed due to being used') 
      throw(:abort)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.master
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :product_id, :price, :size_oz, :master_product_id, :is_active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @related_products = Product.where("master_product_id = ? OR id = ? OR id = ?", @product.id, @product.id, @product.master_product_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.haml
= form_for ['admin', @product] do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description
    = f.rich_text_area :description, class: 'form-control'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'
  .form-group
    = f.label :size, 'Size (oz)'
    = f.text_field :size_oz, class: 'form-control'
  .form-group
    = f.label :master_product_id
    = f.text_field :master_product_id, class: 'form-control'
  .form-group
    = f.label :is_active
    = f.check_box :is_active, class: 'form-control'
  .form-group
    = f.label :images
    
    = f.file_field :images, multiple: true, class: 'form-control-file'
  .actions
    = f.submit 'Save', class: 'btn btn-base'

app/views/admin/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', admin_product_path(@product)
\|
= link_to 'Back', admin_products_path

app/views/admin/products/index.html.haml
%h1 Products

%table.table
  %thead
    %tr
      %th
      %th Name
      %th.text-center Active
      %th ID
      %th Price
      %th Count
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td
          - if product.images.attached?
            - if product.images.first.representable?
              = image_tag product.images.first.representation(resize_to_limit: [80, 80])
        %td= product.name
        %td.text-center
          - if product.is_active?
            = fa_icon "check"
        %td= product.id
        %td= number_to_currency(product.price) if product.price
        %td= product.count
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_admin_product_path(product)
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Product', new_admin_product_path

app/views/admin/products/new.haml
.row
  .col-md-8
    %h1 New product

    = render 'form'