config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: %i[ new create ]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root to: "home#index"

  constraints Clearance::Constraints::SignedIn.new do
    root to: "products#index", as: :signed_in_root
  end

  get 'about' => 'home#about', as: 'about'
  get 'contact' => 'home#contact', as: 'contact'
  resources :products, only: :show
  resources :sessions
  resources :orders, only: %i[ create update show ]
  resources :users, only: %i[ show ]
  get 'cart' => 'orders#cart', as: 'cart'
  post 'add-to-cart' => 'orders#add_to_cart', as: 'add_to_cart'
  post 'remove-from-cart' => 'orders#remove_from_cart', as: 'remove_from_cart'
  get 'shipping' => 'orders#shipping', as: 'shipping'
  get 'checkout' => 'orders#shipping', as: 'checkout'
  get 'review' => 'orders#review', as: 'review'

  resources :charges, only: %i[ create ]
  post 'stripe-webhook' => "charges#stripe_webhook"
  get 'charges/success' => 'charges#success', as: 'success'
  get 'charges/cancel' => 'charges#cancel', as: 'cancel'

  namespace 'admin' do
    resources :products, except: :show
    resources :settings, :users, :promotions
    resources :messages, only: %i[ index show destroy ]
    resources :orders, only: %i[ index update show destroy ]
  end
end

app/controllers/charges_controller.rb
require 'json'
class ChargesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    session = Stripe::Checkout::Session.create({
      customer_email: current_user.email,
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          unit_amount: (@cart_order.net_amount*100).to_i,
          currency: 'usd',
          product_data: {
            name: 'Slime Kangaroo'
          },
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url: "http://slimekangaroo.com/charges/success.html?order_id=#{@cart_order.id}",
      cancel_url: 'http://slimekangaroo.com/charges/cancel.html',
    })

    render json: { id: session.id }
  end

  def stripe_webhook
    event = Stripe::Event.retrieve(params[:id])
    StripeCharge.new(event).process
    render nothing: true, status: 201
  rescue Stripe::APIConnectionError, Stripe::StripeError
    render nothing: true, status: 400
  end

  def success
    order = Order.find_by(id: params[:order_id])
    order.update(charged_at: Time.now) if order
  end

  def cancel
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_stripe_js.html.erb
<script type="text/javascript">
  // Create an instance of the Stripe object with your publishable API key
  var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY'] || Rails.application.credentials.stripe[:publishable_key] %>");
  var checkoutButton = document.getElementById("checkout-button");

  checkoutButton.addEventListener("click", function () {
    fetch("/charges", {
      method: "POST",
    })
      .then(function (response) {
        return response.json();
      })
      .then(function (session) {
        return stripe.redirectToCheckout({ sessionId: session.id });
      })
      .then(function (result) {
        // If redirectToCheckout fails due to a browser or network
        // error, you should display the localized error message to your
        // customer using error.message.
        if (result.error) {
          alert(result.error.message);
        }
      })
      .catch(function (error) {
        console.error("Error:", error);
      });
  });
</script>

app/views/charges/cancel.html.haml
.row
  .col-md-3
  .col-md-6
    #charge-status
      %p
        Checkout was cancelled. You can continue to add items to your
        = link_to 'cart', cart_path
        and check out when you are ready.

app/views/charges/create.html.haml
%h1 Charges#create
%p Find me in app/views/charges/create.html.haml

app/views/charges/success.html.haml
.row
  .col-md-3
  .col-md-6
    #charge-status
      %h2.mb-4.text-center= fa_icon "heart"
      %p
        Thank you! We appreciate your business! We'll start preparing your order for shipment. If you have any questions, please
        = link_to "contact us.", contact_path